#pragma kernel Render

/// <summary>
/// The number of threads per group.
/// </summary>
static const uint2 GroupThreads = uint2(32, 32);

/// <summary>
/// The texture to render.
/// </summary>
RWTexture2D<float4> Texture;

[numthreads(GroupThreads.x, GroupThreads.y, 1)]
void Render(uint3 id : SV_DispatchThreadID)
{
    float2 size;
    Texture.GetDimensions(size.x, size.y);

    Texture[id.xy] = float4(id.xy / size, 0, 1);
}
